language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t chethansh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chethansh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'react-docker'
  env: 'Reactdocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-623039057870'
  bucket_path: 'react-docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
