language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t chethansh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chethansh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-compose-react
  env: Dockercomposereact-env
  bucket_name: elasticbeanstalk-us-east-2-623039057870
  bucket_path: docker-compose-react
  on:
    repo: https://github.com/Chethan-Shivappa/docker-compose-travis.git
    branches: 
      only:
        - master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
